### ISSUE TITLE
기본적으로 지난달것을 계산한다.

### ISSUE THREAD

**Issue by khw7096** [lazypic/git-hours#5]
- 지난달의 시작일, 마감일 기본적용.

**Comment by kybin** [comment]
기본적으로는 전체인게 더 나은것 같아요.

git에 -since가 있으니까 이걸 그대로 넘기면 되지 않을까요?

--since="1 month ago" 처럼요.

**Comment by khw7096** [comment]
저는 견적서를 작성하기 때문에 정확하게 회계상의 월계산을 하려고 생각하고 있어요.
클라이언트쪽 문서(견적서, 계약서)에 들어가는 날짜는 시작과 끝일이 명확한게 좋거든요.

**Comment by kybin** [comment]
그렇게 된다면 일반적으로 사람들이 상상하는 기본값과는 거리가 생길 것 같아요
물론 크게 상관있는건 아니지만 한웅씨가 아까 널리 사용될것 같다고 해서 ㅎㅎㅎ

**Comment by khw7096** [comment]
일단 저 먼저 사용해보면서... 잡아볼께요.
결국 이 프로그램은 저에게는 정확한 견적이 더 중요하다고 생각해서 작성하는 프로그램이거든요.

**Comment by khw7096** [comment]
git 메뉴얼참고.

```
--since, --after : 명시한 날짜 이후의 커밋만 검색한다.
--until, --before : 명시한 날짜 이전의 커밋만 조회한다.
```

현재는 after, before 만 사용중.

**Comment by khw7096** [comment]
용어를 start, end에서 git이 사용하는 since, until로 변경.

**Comment by khw7096** [comment]
-since="1 month ago" 지원.
